Helper page for bpr
vendasta/business-profile-render pull request #14
Opened 2024-05-16 19:08 UTC by MohanRaj168

2024-05-16 19:17 UTC, rajanvijayan requested changes
2 things needs to be updated

2024-05-16 19:17 UTC, rajanvijayan commented on assets/css/style.css
> +.tooltip {
Add `.bpr` prefix

2024-05-16 19:17 UTC, rajanvijayan commented on src/Helper/Page.php
> +        global $wpdb;
Use the `get_option()` function instead of using SQL quires [Ref](https://developer.wordpress.org/reference/functions/get_option/)

2024-05-20 15:15 UTC, MohanRaj168 commented on assets/css/style.css
> +.tooltip {
Updated

2024-05-20 15:15 UTC, MohanRaj168 commented on src/Helper/Page.php
> +        global $wpdb;
get_option() wordpress function is used.

2024-05-21 16:52 UTC, rajanvijayan approved these changes

2024-05-21 16:53 UTC, merged